### ISSUE TITLE
启动Publisher报错

### ISSUE THREAD

**Issue by c-h-h** [yanzhao77/rvListerDemo#2]
启动Publisher 执行 "Tibrv.open(Tibrv.IMPL_NATIVE);" 时报错:"Exception in thread "main" TibrvException[error=901,message=Library not found: tibrvjsd]"
配置了-Djava.library.path后依然报错, 请问怎么解决,方便联系吗,有偿?

**Comment by yanzhao77** [comment]
你没有这个tibrvjsd这个jar包，或者版本错了，这个rv的版本和jar包版本是对应的
